apiVersion: v1
kind: cypress
sauce:
  region: eu-central-1
  concurrency: 10
  metadata:
    tags:
      - e2e
      - release team
cypress:
  version: 13.13.3
  configFile: cypress.config.js

suites:
  - name: 'Chrome on Windows 11'
    browser: 'chrome'
    platformName: 'Windows 11'
    screenResolution: '1440x900'
    config:
      specPattern: ['cypress/e2e/**/*.*']


artifacts:
  download:
    when: always
    match:
      - '*'
    directory: ./artifacts/
